### ISSUE TITLE
Arq issues

### ISSUE THREAD

**Issue by clburlison** [autopkg/clburlison-recipes#17]
TLDR:

- [x] Fix Arq.munki
- [x] Fix Arq.install

----
Arq swapped from a dmg to zip file back in Oct 2019. 

I've patched the .pkg, .download recipes but .install and .munki need extra love.

1. Arq.munki is just flat broken and needs a rewrite to support creating a DMG from the .app extract or using the .pkg.

2. For Arq.install it is installer the package but giving an error message due to the glob search for the package (I think)
```bash
autopkg run -v Arq.install
Processing Arq.install...
URLDownloader
URLDownloader: Item at URL is unchanged.
URLDownloader: Using existing /Users/clburlison/Library/AutoPkg/Cache/local.install.Arq/downloads/Arq.zip
EndOfCheckPhase
Unarchiver
Unarchiver: Guessed archive format 'zip' from filename Arq.zip
Unarchiver: Unarchived /Users/clburlison/Library/AutoPkg/Cache/local.install.Arq/downloads/Arq.zip to /Users/clburlison/Library/AutoPkg/Cache/local.install.Arq/Arq
CodeSignatureVerifier
CodeSignatureVerifier: Verifying code signature...
CodeSignatureVerifier: Deep verification enabled...
CodeSignatureVerifier: Strict verification enabled...
CodeSignatureVerifier: /Users/clburlison/Library/AutoPkg/Cache/local.install.Arq/Arq/Arq.app: valid on disk
CodeSignatureVerifier: /Users/clburlison/Library/AutoPkg/Cache/local.install.Arq/Arq/Arq.app: satisfies its Designated Requirement
CodeSignatureVerifier: /Users/clburlison/Library/AutoPkg/Cache/local.install.Arq/Arq/Arq.app: explicit requirement satisfied
CodeSignatureVerifier: Signature is valid
Versioner
Versioner: Found version 5.17.2 in file /Users/clburlison/Library/AutoPkg/Cache/local.install.Arq/Arq/Arq.app/Contents/Info.plist
AppPkgCreator
AppPkgCreator: BundleID: com.haystacksoftware.Arq
AppPkgCreator: Copied /Users/clburlison/Library/AutoPkg/Cache/local.install.Arq/Arq/Arq.app to /Users/clburlison/Library/AutoPkg/Cache/local.install.Arq/payload/Applications/Arq.app
AppPkgCreator: Connecting
AppPkgCreator: Sending packaging request
AppPkgCreator: Disconnecting
Installer
Installer: Using path '/Users/clburlison/Library/AutoPkg/Cache/local.install.Arq/Arq-5.17.2.pkg' matched from globbed '/Users/clburlison/Library/AutoPkg/Cache/local.install.Arq/Arq*.pkg'.
Installer: Connecting
Installer: Sending installation request
Installer: STATUS:installer: Package name is Arq-5.17.2
Installer: STATUS:installer: Upgrading at base path /
Installer: STATUS:installer:PHASE:Preparing for installation…
Installer: STATUS:installer:PHASE:Preparing the disk…
Installer: STATUS:installer:PHASE:Preparing Arq-5.17.2…
Installer: STATUS:installer:PHASE:Waiting for other installations to complete…
Installer: STATUS:installer:PHASE:Configuring the installation…
Installer: STATUS:installer:STATUS:
Installer: STATUS:installer:%28.704072
Installer: STATUS:installer:PHASE:Writing files…
Installer: STATUS:installer:%51.587788
Installer: STATUS:installer:PHASE:Removing old files…
Installer: STATUS:installer:%57.119374
Installer: STATUS:installer:PHASE:Moving items into place…
Installer: STATUS:installer:PHASE:Validating packages…
Installer: STATUS:installer:%97.750000
Installer: STATUS:installer:STATUS:
Installer: STATUS:installer:PHASE:Finishing the Installation…
Installer: STATUS:installer:STATUS:
Installer: STATUS:installer:%100.000000
Installer: STATUS:installer:PHASE:The software was successfully installed.
Installer: STATUS:installer: The upgrade was successful.
Installer: Disconnecting
Traceback (most recent call last):
  File "/Library/AutoPkg/autopkglib/__init__.py", line 673, in process
    self.env = processor.process()
  File "/Library/AutoPkg/autopkglib/__init__.py", line 480, in process
    self.main()
  File "/Library/AutoPkg/autopkglib/Installer.py", line 181, in main
    self.install()
  File "/Library/AutoPkg/autopkglib/Installer.py", line 127, in install
    self.disconnect()
  File "/Library/AutoPkg/autopkglib/Installer.py", line 177, in disconnect
    self.socket.close()
  File "/Library/AutoPkg/Python3/Python.framework/Versions/Current/lib/python3.7/socket.py", line 420, in close
    self._real_close()
  File "/Library/AutoPkg/Python3/Python.framework/Versions/Current/lib/python3.7/socket.py", line 414, in _real_close
    _ss.close(self)
OSError: [Errno 9] Bad file descriptor
  File "/Library/AutoPkg/autopkglib/__init__.py", line 673, in process
    self.env = processor.process()
[Errno 9] Bad file descriptor
Failed.
Receipt written to /Users/clburlison/Library/AutoPkg/Cache/local.install.Arq/receipts/Arq-receipt-20200224-204042.plist

The following recipes failed:
    Arq.install
        Error in local.install.Arq: Processor: Installer: Error: [Errno 9] Bad file descriptor

The following packages were built:
    Identifier                Version  Pkg Path                                                                  
    ----------                -------  --------                                                                  
    com.haystacksoftware.Arq  5.17.2   /Users/clburlison/Library/AutoPkg/Cache/local.install.Arq/Arq-5.17.2.pkg
```

**Comment by clburlison** [comment]
Both issues resolved with Arq recipes.
